# Generated by Django 5.2.7 on 2026-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
