# Generated by Django 5.2.7 on 2026-01-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_price_bid', to='auctions.bid'),
        ),
    ]
